name: Setup Infrastructure

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  terraform-init-plan:
    name: Terraform Init and Plan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan -out=tfplan

      - name: Post Plan Result
        if: github.event_name == 'pull_request'
        run: |
          terraform show -no-color tfplan > plan.txt
          echo "### Terraform Plan" > comment.md
          cat plan.txt >> comment.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  terraform-environment-apply:
    needs: terraform-init-plan
    name: Terraform Apply with Environment
    runs-on: ubuntu-latest

    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Apply with Environment
        run: terraform apply 
